name: Jekyll Build

on:
  push:
    branches:
      - gh-pages


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check disk space before cleanup
      run: df -h

    - name: Free disk space
      run: |
        sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup /usr/lib/jvm
        sudo apt-get autoremove -y >/dev/null 2>&1
        sudo apt-get autoclean -y >/dev/null 2>&1
        echo "Cleanup completed"

    - name: Check disk space after cleanup
      run: df -h

    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      with:
        source: .
        destination: ./_site
        future: false
        build_revision: 4b918f3336dd8611502b8896abee40a51aabed0c
        verbose: true
        token: ${{ secrets.JEKYLL_BUILD_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: ./_site   # The folder the action should deploy.
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication.
